language: java
jdk:
  - oraclejdk8
before_install: cd core
install: mvn clean test verify -Ptravis-ci

after_success:
- mvn cobertura:cobertura coveralls:report -Ptravis-ci
- mvn clean deploy -Prelease

notifications:
  email:
     - sah4ez32@gmail.com

services:
  - core-erp-vaadin-framework